name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        file: Dockerfile.frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: Dockerfile.backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
